spring:
  application:
    name: seastar-tx-sample-app1
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seastar_tx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#    hikari:
#      maximum-pool-size: 10
#      max-lifetime: 1765000
#      minimum-idle: 10
#      connection-timeout: 30000
  aop:
    proxy-target-class: true
server:
  port: 9831
  servlet:
    context-path: /org
  tomcat:
    max-threads: 3
#logging:
#  level:
#    org.springframework.jdbc: debug
#    org.springframework.transaction: debug
#    org.springframework.dao: debug
#    org.apache.ibatis: debug
#    org.springframework.web: debug
mybatis:
  mapper-locations: classpath:/mapping/*.xml
seastar:
  transaction:
    client:
      url: http://localhost:8851
      local-endpoint: http://localhost:9831