spring:
  application:
    name: seastar-tx-sample-spring-boot
  aop:
    proxy-target-class: true
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seastar_tx?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#logging:
#  level:
#    org.springframework.jdbc.datasource: debug
#    org.springframework.transaction: debug
mybatis:
  mapper-locations: classpath:/mapping/*.xml
server:
  port: 9832
  servlet:
    context-path: /ac
  tomcat:
    max-threads: 3
seastar:
  transaction:
    client:
      url: http://localhost:8851
      local-endpoint: http://localhost:9832