spring:
  application:
    name: seastar-tx-server
  aop:
    proxy-target-class: true
logging:
  level:
    org.springframework.context: debug
    org.springframework.cloud.sleuth: debug
server:
  port: 8851
  tomcat:
    max-threads: 40
#    org.springframework.web: debug
#eureka:
#  client:
#    service-url:
#      defaultZone: http://host-199:8761/eureka
#  instance:
#    ip-address: 192.168.0.189
##    ip-address: host-199
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#    prefer-ip-address: true
#    hostname: ${eureka.instance.ip-address}
#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 5